### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by politicus** [owenwater/alfred-cal#3]
Just tried the workflow and got this error: 

```
Starting debug for 'Productivity Time Calendar'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: 10:19:43 workflow.py:1945 DEBUG    Workflow version : 1.1.0
10:19:43 workflow.py:1951 ERROR    u'alfred.theme.lightlarge'
Traceback (most recent call last):
  File "workflow/workflow.py", line 1946, in run
    func(self)
  File "main.py", line 37, in main
    texts = cal.get_weeks_text(year, month)
  File "cal.py", line 33, in get_weeks_text
    format = Format(self.key, self.path)
  File "format.py", line 14, in __init__
    self.font = self._load_font(key, path)
  File "format.py", line 18, in _load_font
    font = pref['themes'][key]['resultTextFont']
KeyError: u'alfred.theme.lightlarge'
10:19:43 workflow.py:1969 DEBUG    Workflow finished in 0.106 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 10:19:46 workflow.py:1945 DEBUG    Workflow version : 1.1.0
10:19:46 workflow.py:1951 ERROR    u'alfred.theme.lightlarge'
Traceback (most recent call last):
  File "workflow/workflow.py", line 1946, in run
    func(self)
  File "main.py", line 37, in main
    texts = cal.get_weeks_text(year, month)
  File "cal.py", line 33, in get_weeks_text
    format = Format(self.key, self.path)
  File "format.py", line 14, in __init__
    self.font = self._load_font(key, path)
  File "format.py", line 18, in _load_font
    font = pref['themes'][key]['resultTextFont']
KeyError: u'alfred.theme.lightlarge'
10:19:46 workflow.py:1969 DEBUG    Workflow finished in 0.372 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 10:19:46 workflow.py:1945 DEBUG    Workflow version : 1.1.0
10:19:46 workflow.py:1951 ERROR    u'alfred.theme.lightlarge'
Traceback (most recent call last):
  File "workflow/workflow.py", line 1946, in run
    func(self)
  File "main.py", line 37, in main
    texts = cal.get_weeks_text(year, month)
  File "cal.py", line 33, in get_weeks_text
    format = Format(self.key, self.path)
  File "format.py", line 14, in __init__
    self.font = self._load_font(key, path)
  File "format.py", line 18, in _load_font
    font = pref['themes'][key]['resultTextFont']
KeyError: u'alfred.theme.lightlarge'
10:19:46 workflow.py:1969 DEBUG    Workflow finished in 0.107 seconds.
```

**Comment by owenwater** [comment]
Hi @politicus 

I see what the problem is. I'm fixing it right now, sorry for the inconvenience.

Owen

**Comment by owenwater** [comment]
Hi @politicus

I just published a new version of [workflow](https://github.com/owenwater/alfred-cal/blob/master/Calendar.alfredworkflow?raw=true) which shall fix the error.
Also, default width might be too much for `Light Large` theme. You can change it by `cal config` and set the `width` to `9` or `8`.

Owen

**Comment by politicus** [comment]
Working great. Thank you.

**Comment by owenwater** [comment]
Not a problem and sorry for not testing default Alfred theme. Thanks for you report! :smile:
